{% set name = "amazon-sagemaker-jupyter-ai-q-developer" %}
{% set version = "1.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/amazon_sagemaker_jupyter_ai_q_developer-{{ version }}.tar.gz
  sha256: 4538e5fb96edaa1f0718629f499228fc6ea08d4359d69932aa91b804f050c376

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<4.2
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder
    - pip
  run:
    - python >=3.8
    - jupyter_server >=2.0.1,<3
    - jupyter-ai >=2.17.0,<3
    - jupyter-ai-magics >=2.17.0,<3
    - boto3
    - botocore
    - langchain-core
    - aws-embedded-metrics
    - jupyterlab >=4.0,<5
    - sagemaker-jupyterlab-extension-common >=0.1.18,<1
    - faiss-cpu >=1.8.0,<2.0.0,!=1.8.0.post0
    - ipython >=8.18.1,<8.32.0


test:
  requires:
    - pip
    - faiss-cpu >=1.8.0,<2.0.0,!=1.8.0.post0
  imports:
    - amazon_sagemaker_jupyter_ai_q_developer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/sagemaker/
  summary: Amazon SageMaker Jupyter Extension for Q Developer
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bhadrip
    - kumarnzt
    - gogakoreli
