{% set name = "amazon-sagemaker-jupyter-ai-q-developer" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/amazon_sagemaker_jupyter_ai_q_developer-{{ version }}.tar.gz
  sha256: 472a79258ed4707b151a3d630e0be6bcb96d8801a3d7ca1157c19857a0d749f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<4.2
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder
    - pip
  run:
    - python {{ python_min }}
    - jupyter_server >=2.0.1,<3
    - jupyter-ai >=2.17.0,<3
    - jupyter-ai-magics >=2.17.0,<3
    - boto3
    - botocore
    - langchain-core
    - aws-embedded-metrics
    - jupyterlab >=4.0,<5
    - sagemaker-jupyterlab-extension-common >=0.1.18,<1
    - faiss-cpu >=1.8.0,<2
    - "ipython >=8.33.0,<9


test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - amazon_sagemaker_jupyter_ai_q_developer
  commands:
    - pip install faiss-cpu
    - pip check

about:
  home: https://aws.amazon.com/sagemaker/
  summary: Amazon SageMaker Jupyter Extension for Q Developer
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bhadrip
    - kumarnzt
    - gogakoreli
